### ISSUE TITLE
Inconsistency of the GenericModel.predict(data) in ADS 2.6.2 and 2.6.6 versions.

### ISSUE THREAD

**Issue by mingkang111** [oracle/accelerated-data-science#20]
Generic Model's input data has not been serialized into data_dict in v2.6.2. However, in v2.6.6 and above, data passed in GenericModel.predict(data) will be wrapped in an object {"data": <actual passed data>, "data_type": <datatype>} . The score.py generated by v2.6.2 is not able to handle the data given by predict in v2.6.6 and above.

If you have a Model deployed with score.py generated by v2.6.2 and invoked by using predict in v2.6.6 and above, you will see this discrepancy.

**Comment by mayoor** [comment]
Closing this issue. It is fixed in the latest release - 2.7.0
