### ISSUE TITLE
prepare_generic_model() throws error in Oracle Cloud Infrastructure DataScience Jobs

### ISSUE THREAD

**Issue by lyudmil-pelov** [oracle/accelerated-data-science#37]
While using `prepare_generic_model()` with ADS in OCI Data Science Jobs, we experienced following problem:

> "Traceback (most recent call last):"
"  File \"/usr/local/lib/python3.9/site-packages/ads/model/generic_model.py\", line 610, in prepare"
"    xgb_model.prepare("
> "ValueError: `inference_conda_env` must be specified."
> "During handling of the above exception, another exception occurred:"
> "Exception: Could not locate manifest file in the provided conda environment: None. 
> "  File \"/usr/local/lib/python3.9/site-packages/ads/model/common/utils.py\", line 82, in fetch_manifest_from_conda_location"
> "    manifest = fetch_manifest_from_conda_location(conda_prefix)"

It seems that ADS is not picking automatically the Python Version as well as the current Conda Environment used. 

**Workaround**

> to make this code work, specify `inference_conda_env` and `inference_python_version` manually
> and while using `.save` specify `introspection=False`

More about `prepare_generic_model()` can be found here: [ADS Model Catalog](https://docs.oracle.com/en-us/iaas/tools/ads-sdk/latest/user_guide/modelcatalog/modelcatalog.html)

... and here [ads.common.model_export_util.prepare_generic_model](https://docs.oracle.com/en-us/iaas/tools/ads-sdk/latest/ads.common.html#ads.common.model_export_util.prepare_generic_model)

**Comment by mayoor** [comment]
pepare_generic_model is deprecated in favor of `ads.model.generic_model.GenericModel`

Please refer - 
https://accelerated-data-science.readthedocs.io/en/latest/ads.model.html#ads.model.generic_model.GenericModel
https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/frameworks/genericmodel.html#example

**Comment by darenr** [comment]
Closing since resolved
