### ISSUE TITLE
ads.to_sql with replace option not reading complete dataset

### ISSUE THREAD

**Issue by adden666** [oracle/accelerated-data-science#48]
when using ads.to_sql with the if_exists="replace" option the resulting table is not created to reflect the maximum column lengths in the dataset. We only notice this in large datasets > 4m rows.

**Comment by liudmylaru** [comment]
hi! Thank you for reporting an issue. Can you please give us more information. Ideally minimal reproducible testcase. Thank you!

**Comment by darenr** [comment]
@adden666 given the details above we've been unable to reproduce this issue. Please re-open with a reproducible test case, or more details that would allow us to understand the issue better.
