### ISSUE TITLE
Distributed training local test does not support source code from Git repo or OCI object storage

### ISSUE THREAD

**Issue by qiuosier** [oracle/accelerated-data-science#50]
Following the documentation [here](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_training/distributed_training/remote_source_code.html), it allows users to specify source code from Git repo or OCI object storage. However if we try to debug the workload locally using command like `ads opctl run -f train.yaml -b local`, ADS will not do any git clone or copy code from remote to the docker image. Instead, it will still mount the local directory as code directory and run file specified as entry point. This only works if user already have a copy of the code locally (this copy might not be the same as the one from remote uri, as specified in the yaml). Otherwise there will be a `FileNotFound` error.

The behavior might be useful if user is actively developing the code. Then push the code to remote before running the training on data science jobs. However, users are likely to hit the error if they simply want to run the training using code from a remote git repository.

**Comment by darenr** [comment]
Will revist this in the future pending resources coming available to work on it, or if customer experiences similar issue
