### ISSUE TITLE
Allowing all parameters from `CreateApplicationDetails` to be passed through `prepare_app`

### ISSUE THREAD

**Issue by xingyaoc** [oracle/accelerated-data-science#6]
In particular, the Spark configuration properties in OCI dataflow can not be set using `ads.dataflow`, but it's able to be set with [oci.data_flow_models.CreateApplicationDetails](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/data_flow/models/oci.data_flow.models.CreateApplicationDetails.html?highlight=Spark#oci.data_flow.models.CreateApplicationDetails.configuration). Since `prepare_app` already calls `CreateApplicationDetails` it possible to add the rest of the `CreateApplicationDetails` parameters into `prepare_app`?
https://github.com/oracle/accelerated-data-science/blob/d594ed0c8c1365daf4cf9e860daebc760fa9a24b/ads/dataflow/dataflow.py#L171

**Comment by mayoor** [comment]
We have a DataFlow API replacing the old one referred to in this PR. This one lets you pass the configuration as dict. 

Doc link - https://accelerated-data-science.readthedocs.io/en/latest/user_guide/apachespark/dataflow.html#ads-python-sdk
Code - https://github.com/oracle/accelerated-data-science/blob/main/ads/jobs/builders/infrastructure/dataflow.py#L460
