### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'mlx'

### ISSUE THREAD

**Issue by borkur** [oracle/accelerated-data-science#93]
### Oracle-ads version used

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://https://github.com/oracle/accelerated-data-science/releases/) of oracle-ads.

- [X] I have confirmed this bug exists on the main branch of oracle-ads.

- [X] I agree to follow [Code of Conduct](https://github.com/oracle/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When importing 
```
>>> from ads.explanations.explainer import ADSExplainer
```
I get 
```
ModuleNotFoundError: No module named 'mlx'
```

I've searched around and can't find any way to get this resolved.

### How to Reproduce

```python
import ads
from ads.explanations.explainer import ADSExplainer
```

### What was Observed

ModuleNotFoundError: No module named 'mlx'

### What was Expected

The ADSExplainer to be imported

### Version

<details>
'2.8.1'
</details>

**Comment by mingkang111** [comment]
Hi @borkur , thanks for reporting this issue. This `ModuleNotFoundError` has been fixed in the latest version of `oracle-ads` 2.8.3. If you run the `from ads.explanations.explainer import ADSExplainer` in ads==2.8.3, you will see the deprecation message of this module. 
```
NotSupportedError: Working with AutoML has moved from within ADS to working directly with the AutoMLx library. AutoMLx are preinstalled in conda pack automlx_p38_cpu_v2 and later, and can now be updated independently of ADS. AutoMLx documentation may be found at https://docs.oracle.com/en-us/iaas/tools/automlx/latest/html/multiversion/v23.1.1/index.html. Notebook examples are in Oracle's samples repository: https://github.com/oracle-samples/oci-data-science-ai-samples/tree/master/notebook_examples and a migration tutorial can be found at https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_training/automl/quick_start.html .
```
You might find the usage of mlexplainer at https://docs.oracle.com/en-us/iaas/tools/automlx/latest/html/multiversion/v23.1.1/index.html .
